Repository CMPT-276-SPRING-2025/final-project-06-valleys, pull requests merged in 2025-04, with the labels that each got.

#63 feat: restructure unit tests
  src/src/app/api/OpenAI/quiz/route.js
  src/src/app/quiz/page.jsx
  src/tests/openai/integration/quiz.spec.js
  src/tests/openai/unit/scan.spec.js
  src/tests/virus/integration/file.spec.js
  src/tests/virus/integration/ip.spec.js
  src/tests/virus/integration/url.spec.js
  src/tests/virus/unit/file.spec.js
  src/tests/virus/unit/ip.spec.js
  src/tests/virus/unit/url.spec.js
Labels: good first issue, repository, virustotal

#62 Feat update page names
  src/src/app/api/OpenAI/quiz/route.js
  src/src/app/email-analysis/layout.jsx
  src/src/app/email-generator/layout.jsx
  src/src/app/quiz/layout.jsx
  src/src/app/scan/file/layout.jsx
  src/src/app/scan/ip/layout.jsx
  src/src/app/scan/url/layout.jsx
Labels: enhancement, design

#67 feat: create unit and integration test
  src/src/app/api/OpenAI/emailAnalysis/route.js
  src/src/app/email-analysis/page.jsx
  src/src/app/page.js
  src/src/components/footer.jsx
  src/tests/openai/integration/email-analysis.spec.js
  src/tests/openai/unit/email-analysis.spec.js
Labels: testing

#69 feat: add recent virus total scans to localhistory and restructure pages
  src/src/app/scan/file/page.jsx
  src/src/app/scan/ip/page.jsx
  src/src/app/scan/url/page.jsx
  src/src/components/Scanner/FileScanForm.jsx
  src/src/components/Scanner/IPScanForm.jsx
  src/src/components/Scanner/RecentScans.jsx
  src/src/components/Scanner/ScanURLForm.jsx
  src/src/utils/scanHistory.js
Labels: virustotal

#81 feat: Added shield logo on top of title for EmailQuiz page.
  src/src/app/quiz/page.jsx
  src/tests/scan/api/file.spec.js
  src/tests/scan/api/ip.spec.js
  src/tests/scan/api/url.spec.js
  src/tests/scan/integration/file.spec.js
  src/tests/scan/integration/ip.spec.js
  src/tests/scan/integration/url.spec.js
Labels: enhancement, frontend, design
