Repository CMPT-276-SPRING-2025/final-project-06-valleys, pull requests merged in 2025-03, with the labels that each got.

#51 feat: simply build, deploy, and test workflow files, run test on vercel
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: repository

#54 feat: add integration tests for virustotal and organize tests
  src/deploy.yml
  src/tests/scan/api/file.spec.js
  src/tests/scan/api/ip.spec.js
  src/tests/scan/api/url.spec.js
  src/tests/scan/integration/file.spec.js
  src/tests/scan/integration/ip.spec.js
  src/tests/scan/integration/url.spec.js
Labels: testing

#55 feat: add terms and service page and privacy policy page
  src/src/app/email-analysis/page.jsx
  src/src/app/privacy-policy/page.jsx
  src/src/app/terms-and-service/page.jsx
  src/src/components/footer.jsx
  src/src/components/navBar.jsx
Labels: enhancement, frontend

#58 feat: Fixed route.js and page.jsx to load 1 quiz at a time, increasin…
  src/package-lock.json
  src/package.json
  src/src/app/api/OpenAI/quiz/route.js
  src/src/app/page.js
  src/src/app/quiz/page.jsx
Labels: bug, enhancement, api, ai

#59 feat: virustotal progress bars and swap font to Public Sans
  src/package-lock.json
  src/package.json
  src/src/app/(about)/layout.jsx
  src/src/app/(about)/privacy-policy/page.jsx
  src/src/app/(about)/terms-and-service/page.jsx
  src/src/app/globals.css
  src/src/app/layout.js
  src/src/app/page.js
  src/src/app/scan/file/[id]/page.jsx
  src/src/app/scan/ip/[ip]/page.jsx
  src/src/app/scan/url/[url]/page.jsx
  src/src/components/Scanner/LoadingState.jsx
  src/src/components/ui/progress.jsx
Labels: virustotal
